### ISSUE TITLE
Use the Encode function to Encode structures as "" (multi-line literal strings wrapped in three single quotes)

### ISSUE THREAD

**Issue by fengcunwu** [BurntSushi/toml#269] opened 2020-10-16 12:15 UTC
golang 
type Item struct {
	Type  RedisKeyType `toml:"type"`
	Key   string       `toml:"key"`
	Value interface{}  `toml:"value"`
}
encode-------
toml 
type="string"
key="test"
value=''' 
{}
'''

**Comment by ofey404** [comment] 2021-03-17 09:24
I need this feature too! Besides, it's not hard to implement one, maybe I can submit a PR.

**Comment by arp242** [comment] 2021-06-21 05:15
This is a duplicate of #64

**Closed by arp242** 2021-06-21 05:15 UTC
Labels: enhancement
