### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by theoretick** [BurntSushi/toml#268] opened 2020-10-13 17:53 UTC
Hello and thank you for this library.

I just noticed that the recent update was from over 2 years ago.  With over 40 open issues, no support for the most recent TOML 5 spec, and a number of stalled PRs I was hoping to clarify the projects status.

Should this project be given a deprecation notice? Are there any plans to support new features? Are you are looking for new maintainers?

**Comment by BurntSushi** [comment] 2020-10-13 17:55
Duplicate of #265. 

I personally don't have any current plans to do anything with this package, no.

**Comment by theoretick** [comment] 2020-10-13 17:58
@BurntSushi thanks for the reply! Apologies for missing that one before.  

Any thoughts on adding a notice to the README so folks might now there are no plans moving forward on updating the featureset? I've noticed [logrus doing something similar](https://github.com/sirupsen/logrus#logrus---) as it might be helpful knowing the library does not support the most recent specification

**Closed** 2020-10-17 18:33 UTC
Labels: duplicate

**Comment by BurntSushi** [comment] 2020-10-17 18:35
@theoretick IMO, anyone choosing a dependency should do their due diligence on whether it's appropriate to use  or not. That should at least include inspecting commit activity and the issue tracker. It should be clear from that what the current status of this project is. And in particular, the README does state the version of TOML that this package supports near the top.

With that said, you're right, it would be more helpful if I posted an explicit acknowledgment. And that is now done.

Thanks for the prompting.

**Comment by theoretick** [comment] 2020-10-18 22:18
@BurntSushi Agreed and thank you for considering!

**Comment by dfreilich** [comment] 2020-10-27 15:25
Thank you for creating this, @BurntSushi , and the deprecation notice – I actually didn't realize that the TOML spec had continued on development, so the notice was personally helpful for me; and in general, thanks for creating a library that we used for around 2 years with no issues! 🎉
