### ISSUE TITLE
Would you mind dual licensing it under an OSI approved license?

### ISSUE THREAD

**Issue by chanezon** [BurntSushi/toml#165] opened 2017-03-18 00:00 UTC
We're using your excellent library in [containerd](https://github.com/docker/containerd)
We're in the process of donating [containerd to CNCF](https://blog.docker.com/2017/03/docker-donates-containerd-to-cncf/)

The WTFPL license seems to be an issue:-)
https://github.com/cncf/toc/pull/32#pullrequestreview-27665520

Could you dual license it under an OSI approved license like MIT or Apache?
https://opensource.org/licenses/alphabetical

**Comment by BurntSushi** [comment] 2017-03-18 00:04
Dupe of #136.

If I started this project over, I would have chosen Unlicense/MIT, but I can't unilaterally relicense at this point, since it requires approval from all contributors.

If people want to use this library, then they need to convince their legal department that it's OK.

**Closed by BurntSushi** 2017-03-18 00:04 UTC

**Comment by chanezon** [comment] 2017-03-18 00:18
Understood, thank you for the quick response.

**Comment by chanezon** [comment] 2017-03-18 00:39
Do you mind if I maintain a fork under a different license? It seems to be one of the conveniences of the WTFPL https://github.com/chanezon/toml#about-this-fork, and that would allow us to continue using your lib.

**Comment by BurntSushi** [comment] 2017-03-18 00:43
I think as long as there's a pointer back to the original work somewhere in the repo to note that it's a relicensed fork, then I wouldn't mind at all! It sounds like you may need to convince your cohorts though. :-)

**Comment by chanezon** [comment] 2017-03-18 00:45
Thank you, yes I have the first section of the README explain why the fork and pointing back to the original project. Now let's see if I can convince the Linux Foundation:-)
